container: "docker://sethnr/aaeg1000g_admixture:0.02"
#### Config file and sample sheets #####
configfile: "config/config.yaml"
#### reused methods for grabbing GS objects, etc ####
include: "rules/common.smk"

#CHROMS=[1,2,3]
CHROMS=['123',1,2,3]
BIGPOPS=pd.read_table(config["countries"],dtype=str,header=0)['country']

wildcard_constraints:
    chrom=CHROMS,
#    test=TESTS,

rule all:
    input:
#        expand("results/admix_tests/alder_all_summaries.txt",
#            chrom=CHROMS),
#        expand("results/admix_tests/3pop_{chrom}_summaries.txt",
#            chrom=CHROMS),
#        expand("results/admix_tests/3pop_{chrom}_dxy.txt",
#            chrom=CHROMS),
        expand("results/admix_tests/4pop_{chrom}_summaries.txt",
            chrom=CHROMS),

###rule orders ###
ruleorder: tabix_vcf > make_biallelic

##### run admix tests on 4 pops #####

rule make_biallelic:
    input:
        #vcf="results/phase_shapeit/phased_shapeit_{chrom}.vcf.gz",
        #tbi="results/phase_shapeit/phased_shapeit_{chrom}.vcf.gz.tbi"
        vcf="results/vcfs/SNPs/pruned_sites/aegy.wgs.aaa.aaf.mapQ20.GoodSites.chr{chrom}.SNP.refseq.7e6.phased.vcf.gz",
        tbi="results/vcfs/SNPs/pruned_sites/aegy.wgs.aaa.aaf.mapQ20.GoodSites.chr{chrom}.SNP.refseq.7e6.phased.vcf.gz.tbi"
    output:
        vcf=protected("results/admix_bivcf/phased_bi_{chrom}.vcf.gz"),
        tbi=protected("results/admix_bivcf/phased_bi_{chrom}.vcf.gz.tbi")
    log:
        "logs/admix_bivcf/bivcf_{chrom}"
    shell:
        """
        bcftools --version 2>> {log}
        bcftools view -m2 -M2 {input.vcf} -O z -o {output.vcf}
        tabix -pvcf {output.vcf}
        """

#####
# ALDER ADMIXTURE ANALYSIS
#####

rule make_eigenfiles:
    input:
        vcf=ancient("results/admix_bivcf/phased_bi_{chrom}.vcf.gz"),
        tbi="results/admix_bivcf/phased_bi_{chrom}.vcf.gz.tbi",
        chrom_ids=config["chrommap"],
        meta=config["spptable"]
    output:
        geno="results/admix_eigen/eigen_{chrom}.geno",
        snp="results/admix_eigen/eigen_{chrom}.snp",
        ind="results/admix_eigen/eigen_{chrom}.ind"
    resources:
        mem_mb=4000,
        disk_mb=20000,
        h_rt='2:00:00',
    log:
        "logs/admix_eigen/eigen_{chrom}.log",
    params:
        prefix="results/admix_eigen/eigen_{chrom}"
    container: "docker://sethnr/aaeg1000g_analysis:0.02"
    shell:
        """
	    python scripts/VCF_to_eigenstrat.py \
             -v {input.vcf} -m {input.meta} \
              -c {wildcards.chrom} -C {input.chrom_ids} \
              -M country -o {params.prefix}
        """

rule merge_eigenfiles:
    input:
        geno=expand("results/admix_eigen/eigen_{chrom}.geno",chrom=CHROMS),
        snp=expand("results/admix_eigen/eigen_{chrom}.snp",chrom=CHROMS),
        ind="results/admix_eigen/eigen_1.ind"
    output:
        geno="results/admix_eigen/eigen_all.geno",
        snp="results/admix_eigen/eigen_all.snp",
        ind="results/admix_eigen/eigen_all.ind"
    resources:
        mem_mb=4000,
        disk_mb=20000,
        h_rt='1:00:00',
    log:
        "logs/admix_eigen/eigen_merge.log",
    shell:
        """
        cat {input.geno} > {output.geno}
        cat {input.snp} > {output.snp}
        cat {input.ind} > {output.ind}
        """



rule admix_alder:
    input:
        geno="results/admix_eigen/eigen_all.geno",
        snp="results/admix_eigen/eigen_all.snp",
        ind="results/admix_eigen/eigen_all.ind"
    output:
        sum="results/admix_tests/alder_{pop1}_{pop2}_{pop3}_summary.txt",
        raw="results/admix_tests/alder_{pop1}_{pop2}_{pop3}_raw.txt"
    resources:
        mem_mb=4000,
        disk_mb=20000,
        h_rt='4:00:00',
        cpus=4
    threads: 4
    params:
        #chromid=lambda wildcards: get_chrom_id(wildcards),
        file="results/admix_tests/alder_{pop1}_{pop2}_{pop3}.params"
    log:
        "logs/admix_alder/alder_{pop1}_{pop2}_{pop3}.log",
    shell:
        """
        echo genotypename: {input.geno} >./{params.file}
        echo snpname:      {input.snp} >>./{params.file}
        echo indivname:    {input.ind} >>./{params.file}
        echo admixpop:     {wildcards.pop3} >>./{params.file}
        echo refpops:      {wildcards.pop1}\;{wildcards.pop2} >>./{params.file}
        echo raw_outname:  {output.raw} >>./{params.file}
        echo \n                         >>./{params.file}
        echo num_threads:  {threads} >>./{params.file}
        echo mindis:       0.1 >>./{params.file}
        echo binsize:      0.1 >>./{params.file}
        echo jackknife:    NO >>./{params.file}

	    alder -p {params.file} | tee {log} > {output.sum}
        """


rule cat_alder:
    input:
        sums=expand("results/admix_tests/alder_{popstring}_summary.txt",
                    popstring=get_all_admix_3_strings(BIGPOPS))
    output:
        "results/admix_tests/alder_all_summaries.txt"
    log:
        "logs/admix_tests/alder_all.log"
    shell:
        """
        cat {input.sums} | grep DATA | sort -ur > {output}
        """


#####
# 3-POP ADMIXTURE ANALYSIS
#####

rule admix_3pop:
    input:
        vcf=ancient("results/admix_bivcf/phased_bi_{chrom}.vcf.gz"),
        tbi="results/admix_bivcf/phased_bi_{chrom}.vcf.gz.tbi",
        chrom_ids=config["chrommap"],
        meta=config["spptable"]
    output:
        blk=temporary("results/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}_blocks.txt"),
        sum=temporary("results/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}_summary.txt")
    resources:
        mem_mb=8000,
        disk_mb=20000,
        h_rt='1:00:00',
    params:
        prefix="results/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}"
    log:
        "logs/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}.log"
    container: "docker://sethnr/aaeg1000g_analysis:0.02"
    shell:
        """
	    python scripts/run_3pop_tests.py \
            -p1 {wildcards.pop1} -p2 {wildcards.pop2} -p3 {wildcards.pop3} \
            -m {input.meta} -M 'pop' \
            -b 20000 -s 10000 \
            -c {wildcards.chrom} -v {input.vcf} \
            -o {params.prefix}
        """


rule cat_3pop:
    input:
        # sums=expand("results/admix_tests/3pop_{{chrom}}_{popstring}_summary.txt",
        #             popstring=get_all_admix_3_strings(BIGPOPS)),
        # blocks=expand("results/admix_tests/3pop_{{chrom}}_{popstring}_blocks.txt",
        #             popstring=get_all_admix_3_strings(BIGPOPS))
        sums=expand("results/admix_tests/3pop_{{chrom}}_{popstring}_summary.txt",
                    popstring=get_all_admix3_sets_file(config["3pops"])),
        blocks=expand("results/admix_tests/3pop_{{chrom}}_{popstring}_blocks.txt",
                    popstring=get_all_admix3_sets_file(config["3pops"]))
    output:
        sums="results/admix_tests/3pop_{chrom}_summaries.txt",
        blocks="results/admix_tests/3pop_{chrom}_blocks.txt"
    resources:
        mem_mb=32000,
        disk_mb=20000,
        h_rt='1:00:00',
    log:
        "logs/admix_tests/3pop_{chrom}.log"
    shell:
        """
        cat {input.sums} > {output.sums}
        cat {input.blocks} > {output.blocks}
        """


#####
# 3-POP DXY ANALYSIS
#####

rule cf3pop_dxy:
    input:
        vcf=ancient("results/admix_bivcf/phased_bi_{chrom}.vcf.gz"),
        tbi="results/admix_bivcf/phased_bi_{chrom}.vcf.gz.tbi",
        chrom_ids=config["chrommap"],
        meta=config["spptable"]
    output:
        dxy=temporary("results/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}_dxy.txt"),
    resources:
        mem_mb=8000,
        disk_mb=20000,
        h_rt='1:00:00',
    params:
        prefix="results/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}"
    log:
        "logs/admix_tests/dxy_{chrom}_{pop1}_{pop2}_{pop3}.log"
    container: "docker://sethnr/aaeg1000g_analysis:0.02"
    shell:
        """
	    python scripts/run_3pop_dxy.py \
            -p1 {wildcards.pop1} -p2 {wildcards.pop2} -p3 {wildcards.pop3} \
            -m {input.meta} -M 'pop' \
            -b 1000000 -s 1000000 \
            -c {wildcards.chrom} -v {input.vcf} \
            -o {params.prefix}
        """


rule cf3pop_cat:
    input:
        dxy=expand("results/admix_tests/3pop_{{chrom}}_{popstring}_dxy.txt",
                    popstring=get_all_admix3_sets_file(config["3pops"]))
    output:
        dxy="results/admix_tests/3pop_{chrom}_dxy.txt"
    log:
        "logs/admix_tests/3pop_{chrom}.log"
    shell:
        """
        cat {input.dxy} > {output.dxy}
        """


#####
# 4-POP ADMIXTURE ANALYSIS
#####

rule admix_4pop:
    input:
        vcf=ancient("results/admix_bivcf/phased_bi_{chrom}.vcf.gz"),
        tbi=ancient("results/admix_bivcf/phased_bi_{chrom}.vcf.gz.tbi"),
        chrom_ids=config["chrommap"],
        meta=config["spptable"]
    output:
        #blk=temporary("results/admix_tests/4pop_{chrom}_{pop1}_{pop2}_{pop3}_{pop4}_blocks.txt"),
        sum=temporary("results/admix_tests/4pop_{chrom}_{pop1}_{pop2}_{pop3}_{pop4}_summary.txt")
    resources:
        mem_mb=8000,
        disk_mb=20000,
        h_rt='1:00:00',
    params:
        prefix="results/admix_tests/4pop_{chrom}_{pop1}_{pop2}_{pop3}_{pop4}"
    log:
        "logs/admix_tests/4pop_{chrom}_{pop1}_{pop2}_{pop3}_{pop4}.log"
    container: "docker://sethnr/aaeg1000g_analysis:0.02"
    shell:
        """
	    python scripts/run_4pop_tests.py \
            -p1 {wildcards.pop1} -p2 {wildcards.pop2} -p3 {wildcards.pop3}  -p4 {wildcards.pop4} \
            -m {input.meta} -M 'pop' \
            -b 1000000 -s 250000 \
            -c {wildcards.chrom} -v {input.vcf} \
            -o {params.prefix}
        """


rule cat_4pop:
    input:
        sums=expand("results/admix_tests/4pop_{{chrom}}_{popstring}_summary.txt",
                    popstring=get_all_admix4_sets_file(config["4pops"]))
    output:
        sums="results/admix_tests/4pop_{chrom}_summaries.txt"
    resources:
        mem_mb=32000,
        disk_mb=20000,
        h_rt='1:00:00',
    log:
        "logs/admix_tests/4pop_{chrom}.log"
    shell:
        """
        cat {input.sums} > {output.sums}
        """

