container: "docker://sethnr/aaeg1000g_admixture:0.02"
#### Config file and sample sheets #####
configfile: "config/config.yaml"
#### reused methods for grabbing GS objects, etc ####
include: "rules/common.smk"

CHROMS=[1,2,3]
BIGPOPS=pd.read_table(config["countries"],dtype=str,header=0)['country']
TESTS=['alder','3pop']

wildcard_constraints:
    chrom=CHROMS,
    test=TESTS

rule all:
    input:
        expand("results/admix_tests/3pop_{chrom}_summaries.txt",
            chrom=CHROMS),
        expand("results/admix_tests/alder_all_summaries.txt",
            chrom=CHROMS)

###rule orders ###
ruleorder: make_biallelic > tabix_vcf

##### run admix tests on 4 pops #####

rule make_biallelic:
    input:
        vcf="results/phase_shapeit/phased_shapeit_{chrom}.vcf.gz",
        tbi="results/phase_shapeit/phased_shapeit_{chrom}.vcf.gz.tbi"
        #vcf="results/phase_whatshap/whatshap_{chrom}.vcf.gz",
        #tbi="results/phase_whatshap/whatshap_{chrom}.vcf.gz.tbi"
    output:
        vcf="results/admix_bivcf/phased_bi_{chrom}.vcf.gz",
        tbi="results/admix_bivcf/phased_bi_{chrom}.vcf.gz.tbi"
    log:
        "logs/admix_bivcf/bivcf_{chrom}"
    shell:
        """
        bcftools --version 2>> {log}
        bcftools view -m2 -M2 {input.vcf} -O z -o {output.vcf}
        tabix -pvcf {output.vcf}
        """

rule make_eigenfiles:
    input:
        vcf="results/admix_bivcf/phased_bi_{chrom}.vcf.gz",
        tbi="results/admix_bivcf/phased_bi_{chrom}.vcf.gz.tbi",
        chrom_ids=config["chrommap"],
        meta=config["spptable"]
    output:
        geno="results/admix_eigen/eigen_{chrom}.geno",
        snp="results/admix_eigen/eigen_{chrom}.snp",
        ind="results/admix_eigen/eigen_{chrom}.ind"
    resources:
        mem_mb=4000,
        disk_mb=20000,
        h_rt='2:00:00',
    log:
        "logs/admix_eigen/eigen_{chrom}.log",
    params:
        prefix="results/admix_eigen/eigen_{chrom}"
    container: "docker://sethnr/aaeg1000g_analysis:0.02"
    shell:
        """
	    python scripts/VCF_to_eigenstrat.py \
             -v {input.vcf} -m {input.meta} \
              -c {wildcards.chrom} -C {input.chrom_ids} \
              -M country -o {params.prefix}
        """

rule merge_eigenfiles:
    input:
        geno=expand("results/admix_eigen/eigen_{chrom}.geno",chrom=CHROMS),
        snp=expand("results/admix_eigen/eigen_{chrom}.snp",chrom=CHROMS),
        ind="results/admix_eigen/eigen_1.ind"
    output:
        geno="results/admix_eigen/eigen_all.geno",
        snp="results/admix_eigen/eigen_all.snp",
        ind="results/admix_eigen/eigen_all.ind"
    resources:
        mem_mb=4000,
        disk_mb=20000,
        h_rt='1:00:00',
    log:
        "logs/admix_eigen/eigen_merge.log",
    shell:
        """
        cat {input.geno} > {output.geno}
        cat {input.snp} > {output.snp}
        cat {input.ind} > {output.ind}
        """



rule admix_alder:
    input:
        geno="results/admix_eigen/eigen_all.geno",
        snp="results/admix_eigen/eigen_all.snp",
        ind="results/admix_eigen/eigen_all.ind"
    output:
        sum="results/admix_tests/alder_{pop1}_{pop2}_{pop3}_summary.txt",
        raw="results/admix_tests/alder_{pop1}_{pop2}_{pop3}_raw.txt"
    resources:
        mem_mb=4000,
        disk_mb=20000,
        h_rt='1:00:00',
        cpus=4
    threads: 4
    params:
        #chromid=lambda wildcards: get_chrom_id(wildcards),
        file="results/admix_tests/alder_{pop1}_{pop2}_{pop3}.params"
    log:
        "logs/admix_alder/alder_{pop1}_{pop2}_{pop3}.log",
    shell:
        """
        echo genotypename: {input.geno} >./{params.file}
        echo snpname:      {input.snp} >>./{params.file}
        echo indivname:    {input.ind} >>./{params.file}
        echo admixpop:     {wildcards.pop3} >>./{params.file}
        echo refpops:      {wildcards.pop1}\;{wildcards.pop2} >>./{params.file}
        echo raw_outname:  {output.raw} >>./{params.file}
        echo \n                         >>./{params.file}
        echo num_threads:  {threads} >>./{params.file}
        echo mindis:       0.1 >>./{params.file}
        echo binsize:      0.1 >>./{params.file}
        echo jackknife:    NO >>./{params.file}

	    alder -p {params.file} | tee {log} > {output.sum}
        """

rule admix_3pop:
    input:
        vcf="results/admix_bivcf/phased_bi_{chrom}.vcf.gz",
        tbi="results/admix_bivcf/phased_bi_{chrom}.vcf.gz.tbi",
        chrom_ids=config["chrommap"],
        meta=config["spptable"]
    output:
        blk="results/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}_blocks.txt",
        sum="results/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}_summary.txt"
    resources:
        mem_mb=8000,
        disk_mb=20000,
        h_rt='1:00:00',
    params:
        prefix="results/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}"
    log:
        "logs/admix_tests/3pop_{chrom}_{pop1}_{pop2}_{pop3}.log"
    container: "docker://sethnr/aaeg1000g_analysis:0.02"
    shell:
        """
	    python scripts/run_3pop_tests.py \
            -p1 {wildcards.pop1} -p2 {wildcards.pop2} -p3 {wildcards.pop3} \
            -m {input.meta} -M 'country' \
            -c {wildcards.chrom} -v {input.vcf} \
            -o {params.prefix}
        """



rule cat_alder:
    input:
        sums=expand("results/admix_tests/alder_{popstring}_summary.txt",
                    popstring=get_all_admix_3_strings(BIGPOPS))
    output:
        "results/admix_tests/alder_all_summaries.txt"
    log:
        "logs/admix_tests/alder_all.log"
    shell:
        """
        cat {input.sums} | grep DATA | sort -ur > {output}
        """


rule cat_3pop:
    input:
        sums=expand("results/admix_tests/3pop_{{chrom}}_{popstring}_summary.txt",
                    popstring=get_all_admix_3_strings(BIGPOPS))
    output:
        "results/admix_tests/3pop_{chrom}_summaries.txt"
    log:
        "logs/admix_tests/3pop_{chrom}.log"
    shell:
        """
        cat {input.sums} > {output}
        """
