container: "docker://sethnr/aaeg1000g_admixture:0.02"
#### Config file and sample sheets #####
configfile: "config/config.yaml"
#### reused methods for grabbing GS objects, etc ####
include: "rules/common.smk"

CHROMS=[1,2,3]
SAMPLES=pd.read_table(config['samples'],dtype=str,header=0)['sample']
AAF_SAMPLES=pd.read_table("config/AAF_samples.txt",dtype=str,header=0)['sample']
AAA_SAMPLES=pd.read_table("config/AAA_samples.txt",dtype=str,header=0)['sample']

LOCI=pd.read_table("resources/aaeg_hap_loci.txt",dtype=str,header=0)['locusname']


wildcard_constraints:
    chrom=CHROMS
    locusname=LOCI
    
rule all:
    input:
        #expand("results/bams/{sample}.bam",sample=SAMPLES)
        expand("results/locushap_split_vcf/split.{locusname}.{sample}.vcf.gz",
            sample=SAMPLES,
            locusname=LOCI)

##### split and phase vcf #####

rule subset_vcf:
    input:
        vcf=lambda wildcards: get_region_vcf(wildcards)
    output:
        outvcf="results/locushap_vcf/split.{locusname}.vcf.gz",
        outtbi="results/locushap_vcf/split.{locusname}.vcf.gz.tbi"
    resources:
        mem_mb=3000,
        disk_mb=500000,
        bamspace=0
    threads: 1,
    log:
        "logs/locushap_split_vcf/{locusname}.log",
    params:
        regionstring=lambda wildcards: get_region_string(wildcards)
    shell:
        """
        bcftools view -Oz  \
                -o results/locushap_vcf/split.{wildcards.locusname}.vcf.gz \
                          {input.vcf} {params.regionstring} 2>> {log}
        tabix -p vcf results/locushap_vcf/split.{wildcards.locusname}.vcf.gz  2>> {log}
        """

rule split_vcf:
    input:
        vcf="results/locushap_vcf/split.{locusname}.vcf.gz",
        tbi="results/locushap_vcf/split.{locusname}.vcf.gz.tbi"
    output:
        outvcf=temporary("results/locushap_split_vcf/split.{locusname}.{sample}.vcf.gz"),
        outtbi=temporary("results/locushap_split_vcf/split.{locusname}.{sample}.vcf.gz.tbi")
    resources:
        mem_mb=3000,
        disk_mb=500000,
        bamspace=0
    threads: 1,
    log:
        "logs/locushap_split_vcf/{locusname}.{sample}.log",
    shell:
        """
        bcftools view -Oz -s {wildcards.sample} \
                          -o results/locushap_split_vcf/split.{wildcards.locusname}.{wildcards.sample}.vcf.gz \
                          {input.vcf} 2>> {log}
        tabix -p vcf results/locushap_split_vcf/split.{wildcards.locusname}.{wildcards.sample}.vcf.gz  2>> {log}
        """

rule tx_remote_bam:
    input:
        apikey=config["gkey"]
    output:
        bam="results/bams/{sample}.bam",
        bai="results/bams/{sample}.bam.bai"
    resources:
        mem_mb=2000,
        disk_mb=500000,
        #run with, eg, --resources bamspace=10 for 10 sim d/ls
        bamspace=10
    threads: 1,
    params:
        bam=lambda wildcards: get_remote_bam_url(wildcards),
        bai=lambda wildcards: get_remote_bai_url(wildcards),
    container:
        "docker://google/cloud-sdk:latest"
    log:
        "logs/txbam/{sample}.log",
    shell:
        """
        gcloud auth activate-service-account --key-file {input.apikey}
        gsutil cp {params.bam} {output.bam}
        gsutil cp {params.bai} {output.bai}
        #samtools quickcheck {output.bam}
        exit $?
        """



rule whatshap_sample:
    input:
        vcf="results/locushap_split_vcf/split.{chrom}.{sample}.vcf.gz",
        #bam=lambda wildcards: get_remote_bam(wildcards),
        #bai=lambda wildcards: get_remote_bai(wildcards),
        bam="results/bams/{sample}.bam",
        bai="results/bams/{sample}.bam.bai",
        ref=config['fasta'],
        fai=config['fai']
    output:
        #vcf=temporary("results/locushap_whatshap/whatshapp.{chrom}.{sample}.vcf.gz"),
        #tbi=temporary("results/locushap_whatshap/whatshapp.{chrom}.{sample}.vcf.gz.tbi")
        vcf="results/locushap_whatshap/whatshapp.{chrom}.{sample}.vcf.gz",
        tbi="results/locushap_whatshap/whatshapp.{chrom}.{sample}.vcf.gz.tbi"
    resources:
        mem_mb=16000,
        disk_mb=500000,
        bamspace=0,
        h_rt='24:00:00'
    threads: 1,
    log:
        "logs/locushap_whatshap/{chrom}.{sample}.log",
    shell:
        """
          whatshap phase {input.vcf} {input.bam} -r {input.ref} -o {output.vcf} 2>> {log}
          tabix -pvcf {output.vcf} 2>> {log}
        """




rule locushap_shapeit:
    input:
        vcf="results/locushap_whatshap/whatshap.{chrom}.vcf.gz",
        tbi="results/locushap_whatshap/whatshap.{chrom}.vcf.gz.tbi",
        map=config['map']
    output:
        vcf=protected("results/locushap_shapeit/phased_shapeit.{chrom}.vcf.gz"),
    resources:
        mem_mb=16000,
        disk_mb=500000,
        h_rt='96:00:00',
        bamspace=0,
        cpus=10,
	qsub_args='-l highmem  -l avx2=TRUE -l node_type=srm'
    threads: 10
    params:
        chromid=lambda wildcards: get_chrom_id(wildcards)
    log:
        "logs/locushap_shapeit/merge-chr{chrom}.log",
    shell:
        """
        shapeit4 --input {input.vcf} --map {input.map} \
                 --region {params.chromid} \
                 --thread {threads} --log {log} \
                 --output {output.vcf} \
		 --sequencing
        """
