container: "docker://sethnr/aaeg1000g_admixture:0.02"
#### Config file and sample sheets #####
configfile: "config/config.yaml"
#### reused methods for grabbing GS objects, etc ####
include: "rules/common.smk"

CHROMS=[1,2,3]
SAMPLES=pd.read_table(config['samples'],dtype=str,header=0)['sample']
AAF_SAMPLES=pd.read_table("config/AAF_samples.txt",dtype=str,header=0)['sample']
AAA_SAMPLES=pd.read_table("config/AAA_samples.txt",dtype=str,header=0)['sample']

LOCI=pd.read_table("config/aaeg_hap_loci.txt",dtype=str,header=0)['locusname']


wildcard_constraints:
    sample="[^\.]+",
    loci="[^\_]+\d?"

ruleorder:
    region_vcf > exon_vcf > sample_vcf > whatshap > merge_whatshap > shapeit > snpeff > tabix_vcf

rule all:
    input:
        #expand("results/locushap_vcf/locus.{locusname}.vcf.gz",
        #    locusname=LOCI)
        #expand("results/locushap_shapeit/snpeff.{locusname}.vcf.gz",
        #    locusname=LOCI)
        expand("results/locushap_plots/{locusname}.m0.haps.png",
            locusname=LOCI)



##### get remotes #######
rule tx_remote_bam:
    input:
        apikey=config["gkey"]
    output:
        bam="results/bams/{sample}.bam",
        bai="results/bams/{sample}.bam.bai"
    resources:
        mem_mb=2000,
        disk_mb=500000,
        #run with, eg, --resources bamspace=10 for 10 sim d/ls
        bamspace=10
    threads: 1,
    params:
        bam=lambda wildcards: get_remote_bam_url(wildcards),
        bai=lambda wildcards: get_remote_bai_url(wildcards),
    container:
        "docker://google/cloud-sdk:latest"
    log:
        "logs/txbam/{sample}.log",
    shell:
        """
        gcloud auth activate-service-account --key-file {input.apikey}
        gsutil cp {params.bam} {output.bam}
        gsutil cp {params.bai} {output.bai}
        #samtools quickcheck {output.bam}
        exit $?
        """


rule tx_remote_vcf:
    input:
        apikey=config["gkey"]
    output:
        vcf="results/vcfs/raw_{chrom}_{block}.vcf.gz"
    resources:
        mem_mb=2000,
        disk_mb=500000,
        #run with, eg, --resources bamspace=10 for 10 sim d/ls
        bamspace=10
    threads: 1,
    params:
        vcf=lambda wildcards: get_remote_vcf_raw_url(wildcards),
    container:
        "docker://google/cloud-sdk:latest"
    log:
        "logs/txvcf/{chrom}_{block}.log",
    shell:
        """
        gcloud auth activate-service-account --key-file {input.apikey}
        gsutil cp {params.vcf} {output.vcf}
        exit $?
        """



##### split and phase vcf #####

rule region_vcf:
    input:
        vcf=lambda wildcards: get_raw_vcf_from_hapname(wildcards),
        tbi=lambda wildcards: get_raw_tbi_from_hapname(wildcards),
        # vcf=lambda wildcards: get_region_vcf_local(wildcards)
        # tbi=lambda wildcards: get_region_vcf_tbi_local(wildcards)
        #vcf="results/vcfs/aegy.wgs.non-AfrI3.mapQ20.GoodSites.dMM3.chr2.comp.bcf.SNP.vcf.gz",
        #tbi="results/vcfs/aegy.wgs.non-AfrI3.mapQ20.GoodSites.dMM3.chr2.comp.bcf.SNP.vcf.gz.tbi",
        loci=ancient(config["haploci"]),
        meta=config["vcfs"],
    output:
        vcf="results/locushap_vcf/locus.{locusname}.vcf.gz",
        tbi="results/locushap_vcf/locus.{locusname}.vcf.gz.tbi"
    resources:
        mem_mb=3000,
    threads: 1,
    log:
        "logs/locushap_locus_vcf/{locusname}.log",
    params:
        #regionstring="NC_035108.1:94761102-95559560"
        regionstring=lambda wildcards: get_region_string(wildcards),
        geneid=lambda wildcards: get_gene_id_from_name(wildcards)
    shell:
        """
        bcftools view -Oz -o {output.vcf} \
                          {input.vcf} {params.regionstring} 2>> {log}
        tabix -p vcf {output.vcf}  2>> {log}
        """


# rule thinvcf:
#     input:
#         vcf="results/locushap_vcf/locus.{locusname}.vcf.gz",
#         tbi="results/locushap_vcf/locus.{locusname}.vcf.gz.tbi"
#     output:
#         vcf=temporary("results/locushap_vcfthin.{locusname}.vcf.gz"),
#         tbi=temporary("results/locushap_vcf/thin.{locusname}.vcf.gz.tbi")
#     resources:
#         mem_mb=4000,
#         h_rt='1:00:00'
#     threads: 1,
#     log:
#         "logs/locushap_vcf/thin.{locusname}.log",
#     shell:
#         """
#           bcftools view -c 1 -O z -o {output.vcf}  {input.vcf} 2>> {log}
#           tabix -pvcf {output.vcf} 2>> {log}
#         """



rule exon_vcf:
    input:
        vcf="results/locushap_vcf/locus.{locusname}.vcf.gz",
        tbi="results/locushap_vcf/locus.{locusname}.vcf.gz.tbi",
        loci=ancient(config["haploci"]),
        gff=ancient(config["features"]),
    output:
        bed="results/locushap_vcf/exons.{locusname}.bed",
        vcf="results/locushap_vcf/exons.{locusname}.vcf.gz",
        tbi="results/locushap_vcf/exons.{locusname}.vcf.gz.tbi"
    resources:
        mem_mb=3000,
    threads: 1,
    container:
        "docker://sethnr/aaeg1000g_hapnets:0.01"
    log:
        "logs/locushap_vcf/{locusname}.log",
    params:
        geneid=lambda wildcards: get_gene_id_from_name(wildcards)
    shell:
        """
        python scripts/get_gene_merged_exons.py \
            -o {output.bed} \
            -n {params.geneid} \
            -g {input.gff}

        bcftools view -Oz  -R {output.bed} \
                        -o {output.vcf} \
                          {input.vcf} 2>> {log}
        tabix -p vcf {output.vcf}  2>> {log}
        """


rule sample_vcf:
    input:
        vcf="results/locushap_vcf/exons.{locusname}.vcf.gz",
        tbi="results/locushap_vcf/exons.{locusname}.vcf.gz.tbi"
    output:
        vcf=temporary("results/locushap_split_vcf/exons.{locusname}.{sample}.vcf.gz"),
        tbi=temporary("results/locushap_split_vcf/exons.{locusname}.{sample}.vcf.gz.tbi")
        #outvcf="results/locushap_split_vcf/locus.{locusname}.{sample}.vcf.gz",
        #outtbi="results/locushap_split_vcf/locus.{locusname}.{sample}.vcf.gz.tbi"
    resources:
        mem_mb=3000,
    threads: 1,
    log:
        "logs/locushap_split_vcf/{locusname}.{sample}.log",
    shell:
        """
        bcftools view -Oz -s {wildcards.sample} \
                          -o {output.vcf} \
                          --force-samples \
                          {input.vcf} 2>> {log}
        tabix -p vcf {output.vcf} 2>> {log}
        """


rule whatshap:
    input:
        vcf="results/locushap_split_vcf/exons.{locusname}.{sample}.vcf.gz",
        bam="results/bams/{sample}.bam",
        bai="results/bams/{sample}.bam.bai",
        ref=config['fasta'],
        fai=config['fai']
    output:
        vcf=temporary("results/locushap_whatshap/whatshap.{locusname}.{sample}.vcf.gz"),
        tbi=temporary("results/locushap_whatshap/whatshap.{locusname}.{sample}.vcf.gz.tbi")
        #vcf="results/locushap_whatshap/whatshap.{locusname}.{sample}.vcf.gz",
        #tbi="results/locushap_whatshap/whatshap.{locusname}.{sample}.vcf.gz.tbi"
    resources:
        mem_mb=4000,
        h_rt='1:00:00'
    threads: 1,
    log:
        "logs/locushap_whatshap/{locusname}.{sample}.log",
    shell:
        """
          whatshap phase {input.vcf} {input.bam} -r {input.ref} -o {output.vcf} 2>> {log}
          tabix -pvcf {output.vcf} 2>> {log}
        """

rule merge_whatshap:
    input:
        vcfs=expand("results/locushap_whatshap/whatshap.{{locusname}}.{sample}.vcf.gz",
            sample=SAMPLES),
        tbis=expand("results/locushap_whatshap/whatshap.{{locusname}}.{sample}.vcf.gz.tbi",
            sample=SAMPLES)
    output:
        filelist="results/locushap_vcf/filelist.{locusname}.txt",
        vcf=protected("results/locushap_vcf/whatshap.{locusname}.vcf.gz"),
        tbi=protected("results/locushap_vcf/whatshap.{locusname}.vcf.gz.tbi"),
    resources:
        bamspace=0,
        h_rt='6:00:00',
        mem_mb=16000,
        disk_mb=100000,
        cpus=4,
        qsub_args='-l highmem '
    threads:4
    log:
        "logs/phase_whatshap/merge.{locusname}.log",
    shell:
        """
	       echo {input.vcfs} | tr ' ' '\n' > {output.filelist}
	       bcftools merge --threads {threads} -o {output.vcf} -O z -l {output.filelist};  2>> {log}
           tabix -pvcf {output.vcf} 2>> {log}
	"""


rule shapeit:
    input:
        vcf="results/locushap_vcf/whatshap.{locusname}.vcf.gz",
        tbi="results/locushap_vcf/whatshap.{locusname}.vcf.gz.tbi",
#        map=config['map']
    output:
        vcf=protected("results/locushap_shapeit/shapeit.{locusname}.vcf.gz"),
    resources:
        mem_mb=16000,
        disk_mb=10000,
        h_rt='96:00:00',
        bamspace=0,
        cpus=8,
	qsub_args='-l highmem  -l avx2=TRUE -l node_type=srm'
    threads: 8
    params:
        #regionstring="NC_035108.1:94761102-95559560"
        regionstring=lambda wildcards: get_region_string(wildcards)
    log:
        "logs/locushap_shapeit/phased.{locusname}.log",
    shell:
        """
        shapeit4 --input {input.vcf} \
                 --region {params.regionstring} \
                 --thread {threads} --log {log} \
                 --output {output.vcf} \
		         --sequencing
        """


rule snpeff:
    input:
        vcf="results/locushap_shapeit/shapeit.{locusname}.vcf.gz",
        tbi="results/locushap_shapeit/shapeit.{locusname}.vcf.gz.tbi",
#        map=config['map']
    output:
        vcf=protected("results/locushap_shapeit/snpeff.{locusname}.vcf.gz"),
        tbi="results/locushap_shapeit/snpeff.{locusname}.vcf.gz.tbi",
    log:
        "logs/locushap_shapeit/snpeff.{locusname}.log",
    container:
        "docker://sethnr/aaeg1000g_hapnets:0.01"
    params:
        snpeffdir=config["snpeffdir"]
    shell:
        """
        gunzip -dc {input.vcf} >  results/locushap_shapeit/shapeit.{wildcards.locusname}.vcf

        snpEff eff  -no-downstream -no-upstream -no-intergenic -no-intron \
	       	    -canon \
                    -c {params.snpeffdir}/snpEff.config \
		    -nodownload \
		    AaegL5 \
                    results/locushap_shapeit/shapeit.{wildcards.locusname}.vcf | \
        bcftools view -o {output.vcf} -O z 2> {log}

        tabix -p vcf {output.vcf}
        """

rule happlots:
    input:
        vcf="results/locushap_shapeit/snpeff.{locusname}.vcf.gz",
        tbi="results/locushap_shapeit/snpeff.{locusname}.vcf.gz.tbi",
        meta=config["spptable"],
    output:
        vcf5="results/locushap_shapeit/snpeff.{locusname}.m5.vcf.gz",
        haps0="results/locushap_plots/{locusname}.m0.haps.png",
        haps5="results/locushap_plots/{locusname}.m5.haps.png",
    log:
        "logs/locushap_shapeit/haps.{locusname}.log",
    container:
        "docker://sethnr/aaeg1000g_hapnets:0.01"
    params:
        haps0="results/locushap_shapeit/{locusname}.m0.haps.png",
        haps5="results/locushap_shapeit/{locusname}.m5.haps.png",
    shell:
        """
            Rscript scripts/plot_hap_network.R \
        	-i {input.vcf} -o {params.haps0} -m {input.meta} 2>> {log}

            bcftools view -O z -o {output.vcf5} {input.vcf}
            tabix -pvcf {output.vcf5}

            Rscript scripts/plot_hap_network.R \
        	-i {output.vcf5} -o {params.haps5} -m {input.meta} 2>> {log}

        """
