---
output: html_document
editor_options: 
  chunk_output_type: console
---
```{r}
library("tidyverse")

library("patchwork")
library("gridExtra")
library("plyr")
library("zoo")

library("ggrepel")

```



```{r fig.width=18,fig.height=8,dpi=400}
library(maptools)
library(raster)
library(ggmap)

#pop3sum <- read.table("admix_tests/3pop_123_summaries_FCV_NO.txt",col.names=c("p3","p1","p2","chr","f3","f3sd","f3z","f3sig"))
pop3sum <- read.table("admix_tests/3pop_123_summaries.txt",col.names=c("p3","p1","p2","chr","f3","f3sd","f3z","f3sig"))

parents <- c("Franceville","NewOrleans")
#parents <- c("Bantata","HoChiMin")
#parents <- c("Franceville","ElDorado")
pop3sum <- subset(pop3sum,p1 %in% parents & p2 %in% parents)
pop3sum$set <- paste(pop3sum$p3,pop3sum$p1,pop3sum$p2,sep="/")
pop3sum$parent <- paste(pop3sum$p1,pop3sum$p2,sep="/")
pop3sum$f3sig <- as.logical(pop3sum$f3sig)
f3lim=-0.3
pop3sum$f3sig <- pop3sum$f3z < f3lim
write(paste("found",nrow(pop3sum),"summary lines from",1,"files"),stderr())


world <- map_data("world")
meta <- read.table("aegy.wgs.pops.list_display.csv",sep=",",header=T,stringsAsFactors = F) %>% 
                rename_with(tolower) %>% 
                mutate("pop" = gsub("_","",pop))


poptotals <- merge(meta,pop3sum,by.x="pop",by.y="p3")

sigpopsSFvxNO = pop3sum$p3[pop3sum$f3sig]
sigpopsSFvxNO <- sigpopsSFvxNO[!sigpopsSFvxNO %in% parents]

poptotals$sig = F
poptotals$sig[poptotals$pop %in% sigpopsSFvxNO] = T
poptotals$sig[poptotals$pop %in% parents] = NA
poptotals$f3z[poptotals$pop %in% parents] = NA

ggplot() +
    geom_polygon(data = world, aes(x=long, y=lat, group=group), fill='#C7ECD3',color="black",size=0.2) +
    geom_point(data=poptotals, aes(x=long, y=lat, fill=f3z,size=num_bams), fill="grey",shape=21,inherit.aes=F) +
    geom_point(data=subset(poptotals,sig), aes(x=long, y=lat, fill=f3z,size=num_bams), shape=21,inherit.aes=F) +
    geom_text_repel(data=poptotals,aes(x=long, y=lat, label=pop),
                    size=3,max.overlaps = NA  ) +
    coord_fixed(ylim=c(-48,48),xlim=c(-155,140))+
    ggtitle(paste("3-pop results (",parents[1]," / ",parents[2],")",sep="")) +
    scale_fill_gradient(low="red",high="white",na.value="grey") +
    theme(axis.text=element_blank(),
          panel.border=element_rect(fill=NA, color="black"),
          panel.background=element_rect(fill='#C7E6F1', color=NA),
          panel.grid = element_blank(),
          axis.title=element_blank(),
          axis.ticks=element_blank(),
          legend.position="bottom")

poptotals$f3zdisp <- poptotals$f3z
poptotals$f3zdisp[poptotals$f3z>=-0.3] <- NA


ggplot() +
    geom_polygon(data = world, aes(x=long, y=lat, group=group), fill='#C7ECD3',color="black",size=0.2) +
    geom_point(data=subset(poptotals,is.na(latdisp)), aes(x=long, y=lat, fill=f3zdisp,size=num_bams), shape=21,inherit.aes=F) +
    geom_segment(data=subset(poptotals,!is.na(latdisp)), aes(x=longdisp, y=latdisp,xend=long, yend=lat),inherit.aes=F) +
    geom_point(data=subset(poptotals,!is.na(latdisp)), aes(x=longdisp, y=latdisp, fill=f3zdisp,size=num_bams), shape=21,inherit.aes=F) +
    #geom_text_repel(data=subset(poptotals,!is.na(latdisp)), aes(x=longdisp, y=latdisp, label=pop), shape=21,inherit.aes=F) +
    coord_fixed(ylim=c(-48,48),xlim=c(-155,140))+
    ggtitle(paste("3-pop results (",parents[1]," / ",parents[2],")",sep="")) +
    scale_fill_gradient(low="red",high="white",na.value="grey") +
    theme(axis.text=element_blank(),
          panel.border=element_rect(fill=NA, color="black"),
          panel.background=element_rect(fill='#C7E6F1', color=NA),
          panel.grid = element_blank(),
          axis.title=element_blank(),
          axis.ticks=element_blank(),
          legend.position="bottom")


```


```{r  fig.width=6,fig.height=10,dpi=400}
pop3sumAll <- read.table("admix_tests/3pop_123_summaries.txt",col.names=c("p3","p1","p2","chr","f3","f3sd","f3z","f3sig"))
pop3sumAll$set <- paste(pop3sumAll$p3,pop3sumAll$p1,pop3sumAll$p2,sep="/")
pop3sumAll$parent <- paste(pop3sumAll$p1,pop3sumAll$p2,sep="/")
f3lim=-0.258
pop3sumAll$f3sig <- pop3sumAll$f3z < f3lim

pop3sumAll$f3sig[pop3sumAll$p3==pop3sumAll$p2 | pop3sumAll$p3==pop3sumAll$p1] <- F
pop3sumAll$f3[pop3sumAll$p3==pop3sumAll$p2 | pop3sumAll$p3==pop3sumAll$p1] <- NA
pop3sumAll$f3z[pop3sumAll$p3==pop3sumAll$p2 | pop3sumAll$p3==pop3sumAll$p1] <- NA

#pop3sumAll <- pop3sumAll[pop3sumAll$p3 %in% unique(pop3sumAll$p3[pop3sumAll$f3sig]),]

pop3sumAll <- merge(pop3sumAll,meta,by.y="pop",by.x="p3")

parentlevels <- c("Franceville/NewOrleans","Franceville/HoChiMin",
                  "Bantata/HoChiMin","Kedougou/NewOrleans","Kedougou/Clovis",
                  "Franceville/ElDorado","Kedougou/ElDorado","ElDorado/NewOrleans" )
pop3sumAll$parent <- factor(pop3sumAll$parent,levels=parentlevels)

ggplot(pop3sumAll,aes(x=parent,y=p3,fill=f3z,color=f3sig)) + 
         geom_tile() + 
         scale_fill_gradient2(low="red",mid="white",high="white",midpoint = 0,na.value="grey") +
         scale_color_manual(values=c("grey","black")) +
         scale_x_discrete(expand = c(0, 0)) +
         theme(axis.text.x=element_text(angle=45,hjust=1),
               )
    

```
