good_regions: "gs://verily-aaeg1200g/genome_mask_files/snpable_no_outliers.bed.gz"
norep_regions: "gs://verily-aaeg1200g/genome_mask_files/norepeat_5_30x_coverage.bed.gz"
#samples: "config/samples.tsv"

#vcfs: "config_lostruct/vcfs_head.tsv"
samples: "config/samples.txt"

vcfs: "resources/aaeg1000g_full_vcfs.txt"
vcfs_raw: "resources/aaeg1000g_raw_vcfs_tab.txt"
bams: "resources/aaeg1000g_bams.txt"
spptable: "resources/meta_Aaeg1kg_spp.txt"
invtable: "resources/redmond_2020_inversion_calls.txt"
haploci: "resources/aaeg_hap_loci.txt"
features: "resources/VectorBase-59_AaegyptiLVP_AGWG.refseq.gff"


#fasta: "resources/Aedes-aegypti-LVP_AGWG_CHROMOSOMES_ONLY_AaegL5.fa.gz"
#fai: "resources/Aedes-aegypti-LVP_AGWG_CHROMOSOMES_ONLY_AaegL5.fa.gz.fai"
fasta: "resources/Aedes-aegypti-LVP_AGWG_AaegL5_refSeq.fa"
fai: "resources/Aedes-aegypti-LVP_AGWG_AaegL5_refSeq.fa.fai"
chrommap: "resources/chrom_ids.txt"

gkey: "resources/apikey.json"

map: "resources/AaegL5_chr{chrom}.recalc.gmap"
#map: "resources/AaegL5_chr{chrom}.gmap.gz"
#map: "resources/juneja_linkage_REMAP.manual.c{chrom}.txt"

#rawdata_bucket: "gs://verily-aaeg1200g/"

ref:
  # ensembl species name
  species: Aedes_aegypti
  # ensembl release
  release: 100
  # genome build
  build: AaegL5
