container: "docker://sethnr/aaeg1000g_analysis:0.03"
#### Config file and sample sheets #####
configfile: "config/config.yaml"
#### reused methods for grabbing GS objects, etc ####
include: "rules/common.smk"

CHROMS=[1,2,3]
SAMPLES=pd.read_table(config['samples'],dtype=str,header=0)['sample']
AAF_SAMPLES=pd.read_table("config/AAF_samples.txt",dtype=str,header=0)['sample']
AAA_SAMPLES=pd.read_table("config/AAA_samples.txt",dtype=str,header=0)['sample']


rule all:
    input:
        "results/bedcov/all_gene_covs.txt"


##### get remotes #######
rule tx_remote_bam:
    input:
        apikey=config["gkey"]
    output:
        bam="results/bams/{sample}.bam",
        bai="results/bams/{sample}.bam.bai"
    resources:
        mem_mb=2000,
        disk_mb=500000,
        #run with, eg, --resources bamspace=10 for 10 sim d/ls
        bamspace=10
    threads: 1,
    params:
        bam=lambda wildcards: get_remote_bam_url(wildcards),
        bai=lambda wildcards: get_remote_bai_url(wildcards),
    container:
        "docker://google/cloud-sdk:latest"
    log:
        "logs/txbam/{sample}.log",
    shell:
        """
        gcloud auth activate-service-account --key-file {input.apikey}
        gsutil cp {params.bam} {output.bam}
        gsutil cp {params.bai} {output.bai}
        #samtools quickcheck {output.bam}
        exit $?
        """


##### split and phase vcf #####


rule bedcov_sample:
    input:
        bam="results/bams/{sample}.bam",
        bai="results/bams/{sample}.bam.bai",
        bed=config['genebed'],
    output:
        cov="results/bedcov/bedcov.{sample}.cov",
    resources:
        mem_mb=4000,
        h_rt='24:00:00'
    threads: 1,
    log:
        "logs/bedcov1/{sample}.log",
    shell:
        """
          echo {wildcards.sample} > {output.cov}
          samtools bedcov {input.bed} {input.bam} | cut -f 7,7 >> {output.cov}
        """

rule mergecovs:
    input:
        covs=expand("results/bedcov/bedcov.{sample}.cov",sample=SAMPLES),
    output:
        allcov="results/bedcov/all_gene_covs.txt",
    log:
        "logs/mergecovs/merge.log",
    shell:
        """
	       paste {input.covs} > {output.allcov}
	    """
