#from snakemake.remote.GS import RemoteProvider as GSRemoteProvider
#GS = GSRemoteProvider()



container: "docker://sethnr/aaeg1000g_admixture:0.02"
#### Config file and sample sheets #####
configfile: "config/config.yaml"
#### reused methods for grabbing GS objects, etc ####
include: "rules/common.smk"

CHROMS=[1,2,3]
SAMPLES=pd.read_table(config['samples'],dtype=str,header=0)['sample']
AAF_SAMPLES=pd.read_table("resources/AAF_samples.txt",dtype=str,header=0)['sample']
AAA_SAMPLES=pd.read_table("resources/AAA_samples.txt",dtype=str,header=0)['sample']

wildcard_constraints:
    chrom=CHROMS

rule all:
    input:
        expand("results/phase_shapeit/phased_shapeit_{chrom}.vcf.gz",chrom=CHROMS)

rule mergetest:
    input:
        bam="results/phase_whatshap/whatshap_1.vcf.gz"


rule bamtest:
    input:
        bam="results/bams/Debug010_aegypti_Tahiti_FrenchPolynesia_01.bam"

###rule orders ###
ruleorder: whatshap_sample > tabix_vcf


##### split and phase vcf #####

rule split_vcf:
    input:
        vcf=lambda wildcards: get_remote_vcf(wildcards)
    output:
        outvcf=temporary("results/phase_split_vcf/split_{chrom}_{sample}.vcf.gz"),
        outtbi=temporary("results/phase_split_vcf/split_{chrom}_{sample}.vcf.gz.tbi")
    resources:
        mem_mb=3000,
        disk_mb=500000,
        bamspace=0
    threads: 1,
    log:
        "logs/phase_split_vcf/{chrom}.{sample}.log",
    shell:
        """
        bcftools view -Oz -s {wildcards.sample} \
                          -o results/phase_split_vcf/split_{wildcards.chrom}_{wildcards.sample}.vcf.gz \
                          {input.vcf} 2>> {log}
        tabix -p vcf results/phase_split_vcf/split_{wildcards.chrom}_{wildcards.sample}.vcf.gz  2>> {log}
        """

rule tx_remote_bam:
    input:
        apikey=config["gkey"]
    output:
        bam=temporary("results/bams/{sample}.bam"),
        bai=temporary("results/bams/{sample}.bam.bai")
    resources:
        mem_mb=2000,
        disk_mb=500000,
        #run with, eg, --resources bamspace=10 for 10 sim d/ls
        bamspace=10
    threads: 1,
    params:
        bam=lambda wildcards: get_remote_bam_url(wildcards),
        bai=lambda wildcards: get_remote_bai_url(wildcards),
    container:
        "docker://google/cloud-sdk:latest"
    log:
        "logs/txbam/{sample}.log",
    shell:
        """
        gcloud auth activate-service-account --key-file {input.apikey}
        gsutil cp {params.bam} {output.bam}
        gsutil cp {params.bai} {output.bai}
        #samtools quickcheck {output.bam}
        exit $?
        """



rule whatshap_sample:
    input:
        vcf="results/phase_split_vcf/split_{chrom}_{sample}.vcf.gz",
        #bam=lambda wildcards: get_remote_bam(wildcards),
        #bai=lambda wildcards: get_remote_bai(wildcards),
        bam="results/bams/{sample}.bam",
        bai="results/bams/{sample}.bam.bai",
        ref=config['fasta'],
        fai=config['fai']
    output:
        #vcf=temporary("results/phase_whatshap/whatshapp_{chrom}_{sample}.vcf.gz"),
        #tbi=temporary("results/phase_whatshap/whatshapp_{chrom}_{sample}.vcf.gz.tbi")
        vcf="results/phase_whatshap/whatshapp_{chrom}_{sample}.vcf.gz",
        tbi="results/phase_whatshap/whatshapp_{chrom}_{sample}.vcf.gz.tbi"
    resources:
        mem_mb=16000,
        disk_mb=500000,
        bamspace=0,
        h_rt='2:00:00'
    threads: 1,
    log:
        "logs/phase_whatshap/{chrom}_{sample}.log",
    shell:
        """
          whatshap phase {input.vcf} {input.bam} -r {input.ref} -o {output.vcf} 2>> {log}
          tabix -pvcf {output.vcf} 2>> {log}
        """


# rule merge_vcfs:
#     input:
#         vcfs=expand("results/phase_whatshap/whatshapp_{{chrom}}_{sample}.vcf.gz",
#             sample=SAMPLES),
#         tbis=expand("results/phase_whatshap/whatshapp_{{chrom}}_{sample}.vcf.gz.tbi",
#             sample=SAMPLES)
#     output:
#         filelist="results/phase_whatshap/filelist_{chrom}.txt",
#         vcf=protected("results/phase_whatshap/whatshap_{chrom}.vcf.gz"),
#     resources:
#         bamspace=0,
#         h_rt='6:00:00',
#         mem_mb=16000,
#         disk_mb=100000,
#         cpus=4
#     threads:4
#     log:
#         "logs/phase_whatshap/merge-chr{chrom}.log",
#     shell:
#         """
# 	       echo {input.vcfs} | tr ' ' '\n' > {output.filelist}
# 	       bcftools merge --threads {threads} -o {output.vcf} -O z -l {output.filelist};
# 	    """


rule merge_aaa_vcfs:
    input:
        vcfs=expand("results/phase_whatshap/whatshapp_{{chrom}}_{sample}.vcf.gz",
            sample=AAA_SAMPLES),
        tbis=expand("results/phase_whatshap/whatshapp_{{chrom}}_{sample}.vcf.gz.tbi",
            sample=AAA_SAMPLES),
    output:
        vcf=protected("results/phase_whatshap/whatshap_{chrom}_AAAsamples.vcf.gz"),
    resources:
        bamspace=0,
        h_rt='6:00:00',
        mem_mb=8000,
        disk_mb=50000,
        cpus=4
    threads:4
        shell:
            """
    	       echo {input.vcfs} | tr ' ' '\n' > {output.filelist}
    	       bcftools merge --threads {threads} -o {output.vcf} -O z -l {output.filelist};
    	    """

rule merge_aaf_vcfs:
    input:
        vcfs=expand("results/phase_whatshap/whatshapp_{{chrom}}_{sample}.vcf.gz",
            sample=AAF_SAMPLES),
        tbis=expand("results/phase_whatshap/whatshapp_{{chrom}}_{sample}.vcf.gz.tbi",
            sample=AAF_SAMPLES),
    output:
        vcf=protected("results/phase_whatshap/whatshap_{chrom}_AAAsamples.vcf.gz"),
    resources:
        bamspace=0,
        h_rt='6:00:00',
        mem_mb=8000,
        disk_mb=50000,
        cpus=4
    threads:4
        shell:
            """
    	       echo {input.vcfs} | tr ' ' '\n' > {output.filelist}
    	       bcftools merge --threads {threads} -o {output.vcf} -O z -l {output.filelist};
    	    """

rule merge_aaa_aaf:
    input:
        aaa="results/phase_whatshap/whatshap_{chrom}_AAAsamples.vcf.gz"
        aaatbi="results/phase_whatshap/whatshap_{chrom}_AAFsamples.vcf.gz.tbi"
        aaf="results/phase_whatshap/whatshap_{chrom}_AAAsamples.vcf.gz"
        aaftbi="results/phase_whatshap/whatshap_{chrom}_AAFsamples.vcf.gz.tbi"
    output:
        vcf=protected("results/phase_whatshap/whatshap_{chrom}.vcf.gz"),
    resources:
        bamspace=0,
        h_rt='6:00:00',
        mem_mb=16000,
        disk_mb=100000,
        cpus=4
    threads:4
    log:
        "logs/phase_whatshap/merge-chr{chrom}.log",
    shell:
        """
	       bcftools merge --threads {threads} -o {output.vcf} -O z {input.aaa} {input.aaf};
	    """


rule phase_shapeit:
    input:
        vcf="results/phase_whatshap/whatshap_{chrom}.vcf.gz",
        tbi="results/phase_whatshap/whatshap_{chrom}.vcf.gz.tbi",
        map=config['map']
    output:
        vcf=protected("results/phase_shapeit/phased_shapeit_{chrom}.vcf.gz"),
    resources:
        mem_mb=16000,
        disk_mb=500000,
        h_rt='24:00:00',
        bamspace=0,
        cpus=4
    threads: 4
    params:
        chromid=lambda wildcards: get_chrom_id(wildcards)
    log:
        "logs/phase_shapeit/merge-chr{chrom}.log",
    shell:
        """
        shapeit4 --input {input.vcf} --map {input.map} \
                 --region {params.chromid} \
                 --thread {threads} --log {log} \
                 --output {output.vcf}
        """
