good_regions: "gs://verily-aaeg1200g/genome_mask_files/snpable_no_outliers.bed.gz"
norep_regions: "gs://verily-aaeg1200g/genome_mask_files/norepeat_5_30x_coverage.bed.gz"
#samples: "config/samples.tsv"

#vcfs: "config_lostruct/vcfs_head.tsv"
vcfs: "config_lostruct/vcfs_tab.tsv"
spptable: "resources/meta_Aaeg1kg_spp.txt"


#rawdata_bucket: "gs://verily-aaeg1200g/"

ref:
  # ensembl species name
  species: Aedes_aegypti
  # ensembl release
  release: 100
  # genome build
  build: AaegL5
