from snakemake.remote.GS import RemoteProvider as GSRemoteProvider
GS = GSRemoteProvider()


container: "docker://sethnr/aaeg1000g_analysis:0.03"
#### Config file and sample sheets #####
configfile: "config/config.yaml"
#### reused methods for grabbing GS objects, etc ####
include: "rules/common.smk"


#spps = ["aaa", "aaf", "admx"]
spps = ["aaa", "aaf"]
#conts = ["americas", "asia", "eafrica", "wafrica"]
bigcountries = ["Brazil", "USA", "Senegal",
    "Kenya", "Philippines","Gabon","Ghana",
    "SaudiArabia","BurkinaFaso","PuertoRico",
    "Uganda","Trinidad","Vietnam"]

conts = ["eafrica", "wafrica"]


wildcard_constraints:
    block="\d+",
    chrom="\d+",
    #spp="aaa|aaf|admx",
    #cont="americas|asia|wafrica|eafrica",
    #location="aaa|aaf|admx|americas|asia|wafrica|eafrica"
    spp="|".join(spps),
    cont="|".join(conts),
    region="|".join(conts+spps+bigcountries),


rule all:
    input:
        expand("results/lostruct_aims/lostruct_chr{chrid}_{loc}_aims.png",
        chrid=[1,2,3],loc=bigcountries)


###### run lostruct algorithm ########
# blocks of PCAs for each 0.5mb, then a distance matrix
# of first two PCS for each to find similar regions
rule lostruct_run_lostruct:
    input:
        vcf=lambda wildcards: get_remote_vcf(wildcards),
        tbi=lambda wildcards: get_remote_vcf_tbi(wildcards),
        spptable=config["spptable"],
    output:
        pcs="results/lostruct_run/dists_chr{chrom}_{region}.txt",
        png="results/lostruct_run/dists_chr{chrom}_{region}.png",
    resources:
        mem_mb=12000,
        disk_mb=500000,
    threads: 3
    log:
        log="logs/lostruct_run/outliers_chr{chrom}_{region}.log",
    shell:
        """Rscript --vanilla scripts/lostruct_run_lostruct.R \
              {input.vcf} \
              {input.spptable}  \
              {wildcards.chrom} {wildcards.region} \
              {output.pcs} \
              {output.png}\
              2> {log}
        """

# using PC distances, find distinct regions that might be inversions
# output list of candidates and image of regions
rule lostruct_find_inversion_regions:
    input:
        dists="results/lostruct_run/lostruct_chr{chrom}_{region}.txt"
    output:
        txt="results/lostruct_inversion_candidates/lostruct_chr{chrom}_{region}.txt",
        png="results/lostruct_inversion_candidates/lostruct_chr{chrom}_{region}.png",
    resources:
        mem_mb=12000,
        disk_mb=500000,
        h_rt='48:00:00',
        cpus=4
    params:
        prefix="results/lostruct_inversion_regions/regions_chr{chrom}_{region}"
    threads: 4
    log:
        log="logs/lostruct_inversion_regions/candidates-chr{chrom}_{region}.log",
    shell:
        """Rscript scripts/find_inversion_candidates.R \
        	-i {input.dists} \
        	-o {params.prefix} \
        	-c {wildcards.chrom} \
        	-C {threads} \
        	2>> {log}
        """

rule lostruct_assess_inversion_candidates:
    input:
        vcf=lambda wildcards: get_remote_vcf(wildcards),
        tbi=lambda wildcards: get_remote_vcf_tbi(wildcards),
        txt="results/lostruct_inversion_candidates/lostruct_chr{chrom}_{region}.txt",
        spptable=config["spptable"],
    output:
        txt="results/lostruct_inversions/inversions_chr{chrom}_{region}.txt",
        png="results/lostruct_inversions/inversions_chr{chrom}_{region}.png",
        pcs="results/lostruct_inversions/inversions_chr{chrom}_{region}_pcs.Rds",
    resources:
        mem_mb=12000,
        disk_mb=500000,
        h_rt='48:00:00',
        cpus=4
    params:
        prefix="results/lostruct_inversions/regions_chr{chrom}_{region}"
    threads: 4
    log:
        log="logs/lostruct_inversion_regions/candidates-chr{chrom}_{region}.log",
    shell:
        """Rscript scripts/assess_inversion_candidates.R \
        	-i {input.txt} \
        	-o {params.prefix} \
            -v {input.vcf} \
            -s {input.spptable} \
            -c {wildcards.region} \
        	-C {wildcards.chrom} \
        	2>> {log}
        """



# using PC calls for regions thought to be inversions
# get associated SNPs that could be used as AIMs for
# these haplotypes
rule lostruct_get_aims:
      input:
          vcf=lambda wildcards: get_remote_vcf(wildcards),
          tbi=lambda wildcards: get_remote_vcf_tbi(wildcards),
          invs="results/lostruct_inversions/inversions_chr{chrom}_{region}.txt",
          pcs="results/lostruct_inversions/inversions_chr{chrom}_{region}_pcs.Rds",
          spptable=config["spptable"]
      output:
          txt="results/lostruct_aims/lostruct_chr{chrom}_{region}_aim_snps.txt",
      resources:
          mem_mb=4000,
          disk_mb=100000,
      log:
          log="logs/lostruct_aims/get_aims_chr{chrom}_{region}.log",
      shell:
          """Rscript scripts/find_inversion_aims.R \
                -v {input.vcf} \
                -c {wildcards.region} \
                -s {input.spptable} \
                -i {input.invs} \
                -p {input.pcs} \
                -o {output.txt}\
            2> {log}
          """

#plot AIMs for all samples in dataset, ordered by country + putative inversion call
rule lostruct_plot_aims:
      input:
          aims="results/lostruct_aims/lostruct_chr{chrom}_{region}_aim_snps.txt",
          spptable=config["spptable"]
      output:
          aimspic="results/lostruct_aims/lostruct_chr{chrom}_{region}_aims.png",
      resources:
          mem_mb=1000,
          disk_mb=2000,
      log:
          log="logs/lostruct_aims/plot_aims_chr{chrom}_{region}.log",
      shell:
          """Rscript scripts/plot_inversion_aims.R \
          	   -s {input.spptable} \
          	   -i {input.aims} \
               -o {output.aimspic} \
                 2> {log}
          """


###### make inversion plots ######

rule lostruct_plot_pcas:
    input:
        pcs="results/lostruct_pcs/lostruct_chr{chrom}_pcs_{cont}.txt",
        dists="results/lostruct_dists/lostruct_chr{chrom}_dists_{cont}.txt",
        invs=config["invtable"],
    output:
        overlay="results/lostruct_dists/lostruct_chr{chrom}_{cont}_invs_overlay.png",
        comp="results/lostruct_dists/lostruct_chr{chrom}_{cont}_pca_composite.png",
    resources:
        mem_mb=8000,
        disk_mb=300000,
    log:
        log="logs/lostruct_dists/dist-chr{chrom}_{cont}_composite.log",
    shell:
        """Rscript scripts/lostruct_plot_PCAs.R \
        {input.dists} {input.pcs} {input.invs} \
        {wildcards.chrom} {wildcards.cont} {output.overlay} {output.comp} \
        2> {log}
        """
